---
title: Union Church of Monterrey
tagline: We are an intentionally Biblical, interdenominational, international Church
  with English as our primary worship language.
url: https://gogvale.github.io/
baseurl: /UnionChurch
socialimg: "/img/social.jpg"
gmaps_link: https://bit.ly/MapsUnionChurch
phone: "+52 81 8346 0541"
email: UnionChurchMty@gmail.com
address: "Oscar F. Castillón #200, Col. Chepevera, Monterrey, N.L., México"
exclude:
- ".scss"
- README.md
- node_modules
- gruntfile.js
- package.json

social:
  twitter: '#78cdf0'
  facebook: '#537bbd'
  messenger: '#537bbd'
  instagram: '#517fa4'
  youtube: '#d34836'
  snapchat: '#fffc00'
  pinterest:	'#cb2027'
  google: '#dd4b39'


plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - github-pages
theme: jekyll-theme-minimal