# Site settings
title: Union Church of Monterrey
tagline: >-
  We are an intentionally Biblical, interdenominational, international Church with English as our primary worship language.
url: "http://yourwebsite.com" # The base hostname & protocol for your site. Use it if you need absolute URL's

# Social
socialimg: /img/social.jpg # be sure to change this image
facebook: UnionChurchMonterrey
twitter:
github: gogvale
googleplus:
instagram: union-church-of-monterrey

# Contact
phone: +52 81 8346 0541
email: unionchurchmty@gmail.com

# Use this for production
#sass:
#    style: compressed

exclude: [.scss, README.md, node_modules, gruntfile.js, package.json]
