---
title: Union Church of Monterrey
tagline: We are an intentionally Biblical, interdenominational, international Church
  with English as our primary worship language.
url: http://yourwebsite.com
socialimg: "/img/social.jpg"
gmaps_link: https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3595.758215714762!2d-100.35195618452073!3d25.679308518272062!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x866295fdf62e0d25%3A0xfff1c0be96d97a6c!2sOscar%20F.%20Castillon%20200%2C%20Chepevera%2C%2064030%20Monterrey%2C%20N.L.!5e0!3m2!1sen!2smx!4v1584897081864!5m2!1sen!2smx
phone: "+52 81 8346 0541"
email: unionchurchmty@gmail.com
address: Oscar F. Castillón 200 Colonia Chepevera Monterrey, Nuevo León, México
exclude:
- ".scss"
- README.md
- node_modules
- gruntfile.js
- package.json
